In [1]:
import numpy as np

In [2]:
"""
Numpy Array Attribute
"""

print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [3]:
# Random number generator

np.random.seed(0)
arr1= np.random.randint(10, size=6)
print(arr1)
arr2= np.random.randint(10, size=(3,4))
print(arr2)
arr3= np.random.randint(10, size=(3,4,5))
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [4]:
# Attributes
print(arr2)

print("arr2.ndim = ", arr2.ndim)
print("arr2.shape = ",arr2.shape)
print("arr2.size = ",arr2.size)

print("arr2.dtype =", arr2.dtype)
print("arr2.itemsize =", arr2.itemsize)
print("arr2.nbytes = ",arr2.nbytes)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
arr2.ndim =  2
arr2.shape =  (3, 4)
arr2.size =  12
arr2.dtype = int64
arr2.itemsize = 8
arr2.nbytes =  96


In [13]:
"""
Slicing
"""

arr =np.arange(10)
print(arr)

print(arr[2:5])
print(arr[:4])
print(arr[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 1 2 3]
[2 3 4 5 6 7 8 9]


In [14]:
# Multi-dimensional Subarrays

np.random.seed(0)
arr = np.random.randint(10, size=(6, 8))
print(arr)

arr_sub= arr[2:5, 3:7]
print(arr_sub)

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]
[[1 5 9 8]
 [3 5 0 2]
 [3 3 7 0]]


In [7]:
"""
Subarrays as no-copy views
"""
np.random.seed(1)
arr=np.random.randint(10,size=(3,4))
print(arr, '\n')

arr_sub= arr[:2, :2]
print(arr_sub, '\n')

arr_sub[0,0]= 99
print(arr)

arr2=arr.copy()
print(arr2)
arr2[0,0]=1
print(arr2)
print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[99  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]
[[99  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]
[[1 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[99  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]


In [8]:
"""
Reshaping of Arrays
"""

arr= np.arange(1,10)
print(arr, '\n')

# reshape()
grid = arr.reshape(3,3)
print(grid, '\n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [9]:
# np.newaxis

arr= np.array([1,2,3])
print(arr)
print("arr.ndim =", arr.ndim)
print("arr.shape = ",arr.shape)

arr_new = arr[np.newaxis, :]
print(arr_new)
print("arr_new.ndim = ", arr_new.ndim)
print("arr_new.shpae = ", arr_new.shape)

[1 2 3]
arr.ndim = 1
arr.shape =  (3,)
[[1 2 3]]
arr_new.ndim =  2
arr_new.shpae =  (1, 3)


In [10]:
"""
Array Concatenation
"""

# np.concatenate(), np.vstack(), np.hstack()

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array([7,8,9])

arr_total = np.concatenate([arr_1,arr_2,arr_3])
print(arr_total, '\n')

arr_total = np.vstack([arr_1,arr_2,arr_3])
print(arr_total, '\n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [12]:
"""
Array Splitting
"""

arr=[1,2,3,45,67,89,88,3,2,1]
print(arr,'\n')

arr_1,arr_2,arr_3=np.split(arr,[3,5])
print(arr_1,arr_2,arr_3)

[1, 2, 3, 45, 67, 89, 88, 3, 2, 1] 

[1 2 3] [45 67] [89 88  3  2  1]
