In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
lst=[1,2,3,4]

arr=np.array(lst)
print(arr)

[1 2 3 4]


In [3]:
# .dtype attribute

print(arr.dtype)

int64


In [4]:
"""
Size Comparison of ndrray and list objects
"""
from sys import getsizeof

lst = [1,2,3,4,5]
print(getsizeof(lst))

arr = np.array(lst)
print(getsizeof(arr))

112
136


In [10]:
"""
Operations with Numpy Arrays
"""
prices = [35,20,23,19,65,30,16,324]

new_prices = [price-5 for price in prices]
print(new_prices)

# With a ndarray

prices_arr= np.array(prices)
prices_arr = prices_arr - 5
print(prices_arr)

[30, 15, 18, 14, 60, 25, 11, 319]
[ 30  15  18  14  60  25  11 319]


In [12]:
"""
Exercise: Test Scores
"""

t_1 = np.array([93, 95, 81, 90, 87])
t_2 = np.array([79, 90, 88, 93, 91])
t_3 = np.array([87, 72, 65, 90, 82])

t_3_fix = t_3 - 1
print(test_3_fixed)

total1 = t_1 + t_2 + t_3
print(total1)

total2 = total1 / 3
print(total2)

total3 = t_2[3]
print(total3)

test_1 = np.array([t_1[1], t_1[2]])
print(test_1)

[89 87 74 92 94]
[259 257 234 273 260]
[86.33333333 85.66666667 78.         91.         86.66666667]
93
[95 81]


In [14]:
student_scores = np.array([t_1, t_2, t_3])
print(student_scores)

print(student_scores[1, 0])

print(student_scores[: ,3])

[[93 95 81 90 87]
 [79 90 88 93 91]
 [87 72 65 90 82]]
79
[90 93 90]


In [8]:
"""
Logical Operations with Arrays
"""
# masking
a = np.array([1,3,4,5,5,6,67,7,8,9])
mask = a > 5
print(mask)

# select using logical operations
selected = a[a>5]
print(selected)

# combined Logical operations | &
selected = a[(a>6) | (a<4)]
print(selected)

selected = a[(a > 4) & (a<7)]
print(selected)

[False False False False False  True  True  True  True  True]
[ 6 67  7  8  9]
[ 1  3 67  7  8  9]
[5 5 6]
